export const COLORS = {
  bg: "#0A0B0F",
  surface: "#111318",
  card: "#16181F",
  border: "#1E2230",
  accent: "#00E5FF",
  gold: "#FFB800",
  green: "#00FF88",
  orange: "#FF6B35",
  purple: "#A855F7",
  text: "#E8ECF0",
  muted: "#6B7280",
  quality: "#FFB800",
  bridge: "#00E5FF",
  trust: "#00FF88",
  historical: "#6B7280",
  trending: "#FF6B35",
};

export const style: Record<string, any> = {
  app: {
    minHeight: "100vh",
    background: COLORS.bg,
    color: COLORS.text,
    fontFamily: "'Space Mono', 'Courier New', monospace",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    borderBottom: `1px solid ${COLORS.border}`,
    padding: "16px 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    background: COLORS.surface,
  },
  logo: {
    fontSize: "18px",
    fontWeight: "700",
    letterSpacing: "0.1em",
    color: COLORS.accent,
  },
  badge: {
    fontSize: "10px",
    background: `${COLORS.accent}20`,
    border: `1px solid ${COLORS.accent}40`,
    color: COLORS.accent,
    padding: "3px 8px",
    borderRadius: "3px",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
  },
  sectionTitle: {
    fontSize: "11px",
    letterSpacing: "0.2em",
    textTransform: "uppercase",
    color: COLORS.muted,
    marginBottom: "8px",
  },
  h1: {
    fontSize: "28px",
    fontWeight: "700",
    marginBottom: "8px",
    lineHeight: 1.2,
  },
  subtitle: {
    fontSize: "14px",
    color: COLORS.muted,
    marginBottom: "32px",
    lineHeight: 1.6,
  },
  card: {
    background: COLORS.card,
    border: `1px solid ${COLORS.border}`,
    borderRadius: "8px",
    padding: "24px",
    marginBottom: "16px",
  },
  input: {
    width: "100%",
    background: "#0D0F14",
    border: `1px solid ${COLORS.border}`,
    borderRadius: "6px",
    padding: "12px 16px",
    color: COLORS.text,
    fontSize: "14px",
    fontFamily: "'Space Mono', monospace",
    outline: "none",
    boxSizing: "border-box",
    marginTop: "8px",
  },
  textarea: {
    width: "100%",
    background: "#0D0F14",
    border: `1px solid ${COLORS.border}`,
    borderRadius: "6px",
    padding: "12px 16px",
    color: COLORS.text,
    fontSize: "14px",
    fontFamily: "'Space Mono', monospace",
    outline: "none",
    boxSizing: "border-box",
    marginTop: "8px",
    resize: "vertical",
    minHeight: "100px",
  },
  label: {
    fontSize: "11px",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    color: COLORS.muted,
    display: "block",
  },
  btnPrimary: {
    background: COLORS.accent,
    color: "#000",
    border: "none",
    padding: "14px 28px",
    borderRadius: "6px",
    fontSize: "12px",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    fontWeight: "700",
    cursor: "pointer",
    fontFamily: "'Space Mono', monospace",
  },
  btnSecondary: {
    background: "transparent",
    color: COLORS.accent,
    border: `1px solid ${COLORS.accent}`,
    padding: "12px 24px",
    borderRadius: "6px",
    fontSize: "12px",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    cursor: "pointer",
    fontFamily: "'Space Mono', monospace",
  },
  tag: (color: string) => ({
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: "3px",
    fontSize: "11px",
    letterSpacing: "0.1em",
    background: `${color}20`,
    border: `1px solid ${color}50`,
    color: color,
    margin: "3px",
  }),
  grid2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: "16px",
  },
  node: (type: string) => {
    const colorMap: Record<string, string> = {
      Quality: COLORS.quality,
      Bridge: COLORS.bridge,
      Trust: COLORS.trust,
      Historical: COLORS.historical,
      Trending: COLORS.trending,
    };
    const c = colorMap[type] || COLORS.muted;
    return {
      background: `${c}12`,
      border: `1px solid ${c}40`,
      borderRadius: "6px",
      padding: "12px",
      cursor: "pointer",
      transition: "border-color 0.2s",
    };
  },
  statCard: (color: string) => ({
    background: COLORS.card,
    border: `1px solid ${color}30`,
    borderRadius: "8px",
    padding: "20px",
    borderTop: `3px solid ${color}`,
  }),
};
